# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Langue par d√©faut
fr:
  languageCode: fr-fr
  title: "Auguste Doyet | Portfolio Data & IA"
  params:
    description: "Portfolio Data & IA d'Auguste Doyet"
